<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ShartyTools.Core/ShartyTools.Core.csproj" />
    <ProjectReference Include="../../src/ShartyTools.Cli/ShartyTools.Cli.csproj" />
    <ProjectReference Include="../../src/ShartyTools.Desktop/ShartyTools.Desktop.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Avalonia.Headless.XUnit" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
